### ISSUE TITLE
Danish wavenet voices not available?

### ISSUE THREAD

**Issue by DIYtechie** [balsimpson/node-red-contrib-wavenet#7]
Howcome I can't choose a Danish voice? As far as I can see, there are Danish wavenet voices (https://cloud.google.com/text-to-speech/docs/voices?hl=da), but I am not able to choose any in the wavenet node?

![Skærmbillede 2020-04-11 kl  12 16 32](https://user-images.githubusercontent.com/20454469/79079891-12695e00-7d12-11ea-8a82-6c23898c26cc.png)

Running version 3.0.1:
![Skærmbillede 2020-04-12 kl  23 09 22](https://user-images.githubusercontent.com/20454469/79079999-b521dc80-7d12-11ea-9baa-e933cfb98f1e.png)

**Comment by balsimpson** [comment]
Am currently not in a position to access my laptop. Will add the voices as soon as I get a chance.

**Comment by Christiandk1986** [comment]
> Am currently not in a position to access my laptop. Will add the voices as soon as I get a chance.

Hi. Are there any updates on this issue? :-)

**Comment by DIYtechie** [comment]
Any news? Still missing Danish voices.

**Comment by balsimpson** [comment]
Hi...have updated with Danish voices. I have published to NPM, but it might take a while for the update to show. Use `npm install node-red-contrib-wavenet@3.1.1` to force get the latest version.

**Comment by DIYtechie** [comment]
Awesome. Thank you very much. Looking very much forward to trying it. Tried using the npm install 3.1.1 method, but for some reason it's still version 3.0.1 in the palette. Probably my fault, but I assume I will soon be able to update via the manage palette menu :)

**Comment by DIYtechie** [comment]
Just tried again, but for some reason, I still don't see the new version in the palette or on npm? Are you sure it is published to npm and not just github?

**Comment by balsimpson** [comment]
Hmmm..that's strange. Yes, I did publish to npm as you can see from the link below:
https://www.npmjs.com/package/node-red-contrib-wavenet

But it's not showing in the Node-RED palette as updated. Let me check.

**Comment by balsimpson** [comment]
Check it now..

**Comment by DIYtechie** [comment]
It works! Thank you very much. Much appreciated @balsimpson  :)

![Skærmbillede 2020-06-21 kl  14 46 57](https://user-images.githubusercontent.com/20454469/85224962-11b60d80-b3ce-11ea-9c44-a4f1b3cce6d1.png)
![Skærmbillede 2020-06-21 kl  14 50 32](https://user-images.githubusercontent.com/20454469/85225034-9739bd80-b3ce-11ea-9614-c494b50d2573.png)
